const categoriesArray = [
  "Prompts",
  "Paraphraser",
  "Dating",
  "Personalized videos",
  "Religion",
  "Music",
  "Developer tools",
  "Education assistant",
  "Text to speech",
  "Copywriting",
  "Image editing",
  "Real estate",
  "SQL",
  "Avatars",
  "Startup tools",
  "Video editing",
  "E-commerce",
  "Presentations",
  "General Writing",
  "No code",
  "Story teller",
  "Transcriber",
  "Email Assistant",
  "Fitness",
  "Sales",
  "Art",
  "Fashion",
  "Image generator",
  "3D",
  "Audio editing",
  "Summarizer",
  "Social media assistant",
  "Spreadsheets",
  "Finance",
  "SEO",
  "Legal assistant",
  "Logo generator",
  "Design assistant",
  "Human resources",
  "Video generator",
  "Customer support",
  "Code assistant",
];

console.log(categoriesArray);

export default categoriesArray;
